"""Add btc_timestampdata

Revision ID: 50f87307c365
Revises: 
Create Date: 2024-05-25 09:04:46.420517

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50f87307c365"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "btc_timestampdata",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("price", sa.Numeric(scale=6), nullable=False),
        sa.Column("volume_5000_bids", sa.Float(), nullable=False),
        sa.Column("volume_5000_asks", sa.Float(), nullable=False),
        sa.Column("weighted_avg_bid_price", sa.Float(), nullable=False),
        sa.Column("weighted_avg_ask_price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    op.create_table(
        "sap_timestampdata",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("price", sa.Numeric(scale=6), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sap_timestampdata")
    op.drop_table("btc_timestampdata")
    # ### end Alembic commands ###
